<a href="https://colab.research.google.com/github/dianakang/K_digital_likelion/blob/master/20201228_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 9.1 클래스

## 9.1.1 클래스 정의

In [1]:
## 함수와 변수가 똑같은 구조를 계속 여러번 써야하니깐 불편함 -> 이걸 하나로 묶어서 설계도를 만들자!

In [2]:
# 클래스 쓰는 방법
## 1. class를 입력하고
## 2. 대문자로 시작하는 클래스의 이름을 작성

## 3. 안에 들어갈 함수와 변수 설정 / def __init__ -> 처음 클래스가 만들어질 때 값을 설정
## 4. 그 밑에는 함수가 있고, 그 함수에 self가 들어가 있음 -> 초기화 함수

In [3]:
# class 클래스명:         --> ※ 주의: 첫 글자는 대문자
#     변수명 = 값
#     변수명 = 값
#     def 함수명(self, 전달값_변수명, ...):
#         코드 1
#         코드 2

In [4]:
import os
os.chdir("/content/drive/MyDrive/4주차/dataset")   # chdir = change(변경해라) + dir(파일경로)
os.getcwd()        # getcwd() = 파일 경로 확인 메서드

'/content/drive/MyDrive/4주차/dataset'

In [5]:
os.getcwd() # getcwd() = 파일 경로 확인 메서드

'/content/drive/MyDrive/4주차/dataset'

In [6]:
from my_email import Email

e = Email()
e.sender = "younjung952@likelion.org"
recv_list = ['younjung952@gmail.com', 'younjung952@hufs-gsuite.kr','dianakang0106@gmail.com']

for recv in recv_list:
    e.send_mail(recv, "Welcome!","This is contents")

From:	younjung952@likelion.org
To:	younjung952@gmail.com
Subject:Welcome!
Contents
This is contents
--------------------
From:	younjung952@likelion.org
To:	younjung952@hufs-gsuite.kr
Subject:Welcome!
Contents
This is contents
--------------------
From:	younjung952@likelion.org
To:	dianakang0106@gmail.com
Subject:Welcome!
Contents
This is contents
--------------------


In [7]:
# 케이틀린 / 빠른 평타 기반 / 총을 쏠 수 있음.
name = "케이틀린"
hp = 400
damage = 55

print("{0} 챔피언이 소환사의 협곡에 참여하였습니다.".format(name))
print("체력{0}, 공격력{1} \n".format(hp, damage))

케이틀린 챔피언이 소환사의 협곡에 참여하였습니다.
체력400, 공격력55 



In [8]:
# 진 / 느린 평타 기반 / 강력한 총을 쏠 수 있음
J_name = "진"
J_hp = 550
J_damage = 70

print("{0} 챔피언이 소환사의 협곡에 참여하였습니다.".format(J_name))
print("체력{0}, 공격력{1} \n".format(J_hp, J_damage))

진 챔피언이 소환사의 협곡에 참여하였습니다.
체력550, 공격력70 



In [9]:
def attack(name, location, damage):
  print("{0} : {1} 방향으로 상대 챔피언을 공격합니다. [공격력 {2}".format(\
                                                        name,location,damage))
attack(name, "바텀", damage)
attack(J_name, "바텀", J_damage)


케이틀린 : 바텀 방향으로 상대 챔피언을 공격합니다. [공격력 55
진 : 바텀 방향으로 상대 챔피언을 공격합니다. [공격력 70


In [10]:
J_name_2 = "알엠"
J_hp_2 = 600
J_damage_2 = 80

attack(name, "바텀", damage)
attack(J_name, "바텀", J_damage)
attack(J_name_2, "바텀", J_damage_2)

케이틀린 : 바텀 방향으로 상대 챔피언을 공격합니다. [공격력 55
진 : 바텀 방향으로 상대 챔피언을 공격합니다. [공격력 70
알엠 : 바텀 방향으로 상대 챔피언을 공격합니다. [공격력 80


In [11]:
class Unit:
  def __init__(self, name, hp, damage):
    self.name = name
    self.hp = hp
    self.damage = damage
    print("{0} 챔피언이 소환사의 협곡에 참여하였습니다.". format(self.name))
    print("체력 {0}, 공격력 {1}".format(self.hp, self.damage))

Jhin1 = Unit("진", 550, 70)
Jhin2 = Unit("알엠", 600, 80)
Caitlyn = Unit("케이틀린", 400, 55)

## 클래스에는 꼭 입력해야할 변수를 모두 입력해야 한다. 
## 예를 들어, "진", 550, 70 중 하나라도 빠뜨린다면 에러를 출력한다.

진 챔피언이 소환사의 협곡에 참여하였습니다.
체력 550, 공격력 70
알엠 챔피언이 소환사의 협곡에 참여하였습니다.
체력 600, 공격력 80
케이틀린 챔피언이 소환사의 협곡에 참여하였습니다.
체력 400, 공격력 55


In [12]:
# 유미, 서포터 챔피언, 숨기 기능(상대방이 공격 불가능)
Yuumi_1 = Unit("유미", 300, 10)
print("챔피언 이름: {0}, 공격력 : {1}".format(Yuumi_1.name, Yuumi_1.damage))

유미 챔피언이 소환사의 협곡에 참여하였습니다.
체력 300, 공격력 10
챔피언 이름: 유미, 공격력 : 10


In [13]:
# 서포팅 상태 : 아군 챔피언에게 붙어있기에 상대방은 공격 불가능
Yuumi_2 = Unit("유미", 300, 10)
Yuumi_2.impossible_to_attack = True  
## 클래스 변수를 생성하는 과정에서 기존에 없던 매개변수(impossible_to_attack)를 생성할 수도 있다.

if Yuumi_2.impossible_to_attack == True:
  print("{0}은(는) 현재 서포팅 상태입니다.". format(Yuumi_2.name))  # 서포팅 = 공격X

유미 챔피언이 소환사의 협곡에 참여하였습니다.
체력 300, 공격력 10
유미은(는) 현재 서포팅 상태입니다.


In [14]:
class AttackUnit:
  def __init__(self, name, hp, damage):
    self.name = name  # 초기화
    self.hp = hp   # hp = 체력
    self.damage = damage

  def attack(self, location):   # 공격기능을 수행하는 메서드(함수)
    print("{0} : {1} 방향으로 상대방 챔피언을 공격합니다. [공격력 {2}] "\
          .format(self.name, location, self.damage))  
  ## attack(self, location)에서 이미 정의했으므로 self를 써줄 필요가 없다.
  
  def damaged(self, damage):   # 공격을 입는 경우에 대한 메서드
    print("{0} : {1} 데미지를 입었습니다. ". format(self.name, damage))
    self.hp -= damage   # self.hp = self.hp - damage
    print("{0} : 현재 체력은 {1} 입니다.". format(self.name, self.hp))
    if self.hp <= 0:     # 게임에서 hp(체력)가 0이면 죽음
      print("{0} : 처치당하였습니다.".format(self.name))

# 카이사, 빠른 평타 기반, 빠르게 이동가능
KaiSa = AttackUnit("카이사", 450, 55)
KaiSa.attack("탑")

# 상대 챔피언에게 공격을 2번 받음
KaiSa.damaged(250)
KaiSa.damaged(250)

     

카이사 : 탑 방향으로 상대방 챔피언을 공격합니다. [공격력 55] 
카이사 : 250 데미지를 입었습니다. 
카이사 : 현재 체력은 200 입니다.
카이사 : 250 데미지를 입었습니다. 
카이사 : 현재 체력은 -50 입니다.
카이사 : 처치당하였습니다.


## 9.1.2 상속

In [15]:
class Unit:
  def __init__(self, name, hp):    # 초기화 함수
    self.name = name
    self.hp = hp

class AttackUnit(Unit):
  def __init__(self, name, hp, damage):  # AttackUnit의 초기화 함수
    Unit.__init__(self, name, hp)        # Unit의 초기화 함수
    self.damage = damage

  def attack(self, location):   # 공격기능을 수행하는 메서드(함수)
    print("{0} : {1} 방향으로 상대방 챔피언을 공격합니다. [공격력 {2}] "\
          .format(self.name, location, self.damage))  
  ## attack(self, location)에서 이미 정의했으므로 self를 써줄 필요가 없다.
  
  def damaged(self, damage):   # 공격을 입는 경우에 대한 메서드
    print("{0} : {1} 데미지를 입었습니다. ". format(self.name, damage))
    self.hp -= damage   # self.hp = self.hp - damage
    print("{0} : 현재 체력은 {1} 입니다.". format(self.name, self.hp))
    if self.hp <= 0:     # 게임에서 hp(체력)가 0이면 죽음
      print("{0} : 처치당하였습니다.".format(self.name))

## 9.1.3 다중상속

In [16]:
## 정글 유닛 / 중립 몬스터 / 챔피언을 공격하거나 공격하지 않을 수도 있음
class Jungle:   # 공격 x
  def __init__(self, dash_speed):
    self.dash_speed = dash_speed

  def dash(self, name, location):
    print("{0} : {1} 방향으로 회피를 합니다. [속도 {2}]"\
          .format(name, location, self.dash_speed))
    
class JungleAttackUnit(AttackUnit, Jungle):   # 다중상속
  def __init__(self, name, hp, damage, dash_speed):
    AttackUnit.__init__(self, name, hp, damage)
    Jungle.__init__(self, dash_speed)

In [17]:
Red_1 = JungleAttackUnit("레드", 1200, 50, 10)
Red_1.dash(Red_1.name, "공격받은 방향의 반대")

레드 : 공격받은 방향의 반대 방향으로 회피를 합니다. [속도 10]


# 9.2 벡터와 행렬

In [18]:
## 머신러닝은 대량의 데이터를 사용해 학습한다.
## 따라서 데이터를 효율적으로 다루는 구조가 필요한데, 이 때 신경망의 '벡터'와 '행렬'이 필요하다.

In [19]:
# 스칼라의 개념
## 정수와 소수 등 숫자의 크기만을 나타내는 0차원 표현

## 9.2.1 벡터(vector)

In [20]:
# 벡터(vector)의 개념
## 크기 뿐만 아니라 방향도 있는 1차원, 2차원 표현
## 크게 '평면에서의 벡터(1차원)'와 '공간에서의 벡터(2차원)'으로 나뉜다. 

In [21]:
# 벡터 알아보기
## 벡터는 알파벳 위에 화살표를 사용하여 표현하거나, a,b(굵은 알파벳)으로 표현한다.
## 벡터의 크기와 방향은 좌표축 성분으로 나누어 표현한다.
## 2차원 = [2,1] --- x좌표, y좌표 / 3차원 = [3,2,1]  ---- x좌표, y좌표, z좌표
## 벡터의 원소를 [] 대신 ()을 이용하여 표현하기도 한다.

In [22]:
# 원소 나열하기
## 가로로 나열 = 행 벡터(row vector) / 세로로 나열 = 열 벡터(column vector)

## 9.2.2 행렬(matrix)

In [23]:
# 행렬(matrix)의 개념
## 행 벡터 혹은 열 벡터를 합해 여러 개 원소를 가로 혹은 세로로 나열한 것
## 행렬은 A처럼 '굵은 대문자'로 표현하고, 원소는 []안에 넣는다.

In [24]:
# 텐서(tensor)의 개념
## '여러 개 벡터'를 '곱 연산'을 사용해 복합적으로 연결시킨 구조
## 보통 두 벡터의 행렬 곱셈 결과가 텐서가 되는 텐서곱 연산을 사용한다.

In [25]:
#----------------------------------------------------------------------------

In [26]:
## 머신러닝에서 행렬 데이터는 넘파이의 ndarray(N dimension Array)라는 클래스를 사용한다.
## 이는 array함수로 다차원 배열을 처리하는 객체를 만들어 행렬을 쉽게 생성한다.
## 행렬을 생성할 때는 다차원 리스트를 사용한다.

In [27]:
import numpy as np

a = np.array([2,1])   # 벡터(vector) ----> 굵은 소문자(a)로 표현
print(a)

b = np.array([3,2,1])  # 벡터
print(b)

A = np.array([[2,4,1], [6,3,5]])  # 행렬(matrix) ---> 굵은 대문자(A)로 표현
print(A)

[2 1]
[3 2 1]
[[2 4 1]
 [6 3 5]]


## 9.2.3 벡터의 연산

### (1) 합(+),차(-) 연산

In [28]:
# 벡터의 합과 차는 서로 대응하는 원소 각각을 더하거나 뺀다. -> 결과값은 벡터이다.
# 벡터의 크기는 피타고라스 정리(절댓값)를 사용해 계산한다.

In [29]:
import math
a = np.array([3,2])
b = np.array([1,4])

print(a+b)  # 벡터의 합
print(a-b)  # 벡터의 차
print(np.linalg.norm(a)) # 벡터 a의 크기
print(np.linalg.norm(b)) # 벡터 b의 크기

# 벡터의 크기를 함수로 계산
def norm(x):
  return math.sqrt(sum([i ** 2 for i in x]))

print(norm(a))  # 벡터 a의 크기
print(norm(b))  # 벡터 b의 크기

## norm()함수를 살펴보면, 벡터의 크기는 각 리스트를 제곱한 값의 합에 제곱근을 계산하는 것이다.
## 즉, 넘파이를 사용하지 않아도 계산할 수 있다.

[4 6]
[ 2 -2]
3.605551275463989
4.123105625617661
3.605551275463989
4.123105625617661


### (2) 곱(x) 연산

In [30]:
# 벡터의 곱셉은 '내적'이라고 한다.
# 내적을 계산하는 방법은 대응하는 원소끼리 곱한 후 합을 계산한다. -> 결과값은 스칼라(숫자)이다.

In [31]:
## 두 벡터가 수직이면, 벡터의 내적은 항상 0이다. ex) a = [2 1], b = [-1 2] = 0
## 내적이 양수이면 두 벡터가 이루는 각이 90도보다 작고, 음수이면 90도보다 크다.
## 파이썬으로 벡터의 내적을 계산하는 방법은 두 가지가 있다.
## 하나는 내적 계산으로 리스트 안 요소를 차례로 곱해서 더하는 것이고, 다른 하나는 넘파이의 dot함수를 사용하는 것이다.
##           ㄴ'코시 - 슈바르츠 부등식' -> 최솟값 계산할 때 유용,,         

In [32]:
# 넘파이의 dot함수 이용
import numpy as np

a = np.array([3,2])
b = np.array([1,4])
print(a.dot(b))

c = np.array([2,1])
d = np.array([-1,2])
print(c.dot(d))

11
0


## 9.2.4 행렬의 연산

In [33]:
# 행렬은 행 개수가 m이고 열 개수가 n인, m x n 행렬로 표현한다.
## 행 개수와 열 개수가 같으면 '정사각행렬'이라고 한다. (ex, 2차 정사각행렬, 3차 정사각행렬)

### (1) 합(+), 차(-)의 연산

In [34]:
# 두 행렬의 합과 차는 각 행렬의 같은 위치 원소를 더하거나 빼서 계산한다.
# 합과 차를 계산할 때는 행과 열의 개수가 같아야한다.

import numpy as np

X = np.array([[1,2,3], [3,4,5]])
Y = np.array([[3,4,5], [4,5,6]])
print(X+Y)
print(X-Y)

[[ 4  6  8]
 [ 7  9 11]]
[[-2 -2 -2]
 [-1 -1 -1]]


### (2) 곱(x)의 연산

In [35]:
# 일반적인 행렬은 곱을 계산할 때는 왼쪽 행렬의 '행'과 오른족 행렬의 '열'을 곱한다.
# 두 행렬 A,B의 곱 A x B는 AB로 표기한다.

In [36]:
# 행렬의 곱셈은 왼쪽 행렬의 '열 개수'와 오른쪽 행렬의 '행 개수'가 같아야 한다.
# 보통 왼쪽이 m * k 행렬이고 오른쪽이 k * n 행렬일 때, 행렬의 곱 결과는 m * n 행렬이다. 

In [37]:
## array 함수로 행렬을 만들었다면 dot 함수로 행렬의 곱을 쉽게 계산할 수 있다.
A = np.array([[1,2,3],[3,4,5]])
B = np.array([[3,4],[4,5],[5,6]])
print(A.dot(B))

## 넘파이에서 행렬을 다루는 matrix 함수를 사용해서 행렬을 만들 수도 있다.
C = np.matrix([[1,2,3], [3,4,5]])
D = np.matrix([[3,4],[4,5],[5,6]])
print(C * D)  # matrix 함수로 행렬을 만들어 변수에 저장하면, * 연산자를 사용할 수 있다는 장점도 있다.

[[26 32]
 [50 62]]
[[26 32]
 [50 62]]


In [ ]:
# 그러나 행렬의 곱에서는 잊으면 안되는 사실이 하나 있다. 바로 AB와 BA의 계산 결과가 일치하지 않는다는 점이다.

In [37]:
# 단위 행렬
## 왼쪽 위에서 오른쪽 아래 대각선 방향의 행렬 원소가 1이고, 나머지 원소가 0인 행렬 -> 보통 E나 I같은 기호로 표현함

In [37]:
# 전치 행렬
## 행렬의 행과 열을 교환한 행렬 -> 딥러닝의 활성화 함수 역전파 연산 과정에서 주요하게 사용된다.