<a href="https://colab.research.google.com/github/dianakang/helloTensorflow/blob/master/20201215.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.1 Hello World

In [42]:
print("Hello World")

Hello World


#1.2 Hello 텐서플로 2.0

In [43]:
try:
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

In [44]:
import tensorflow as tf
print(tf.__version__)

2.3.0


# 1.3 난수 생성

In [45]:
# 난수 = 무작위로 추출한 값

## 1.3.1 균일분포(uniform함수)

In [46]:
# tr.random.uniform 함수를 불러오면 균일분포(uniform distribution)의 난수를 얻을 수 있다.
rand = tf.random.uniform([4],0,1)   # []: 결과값의 shape, 0 : 최소값, 1: 최대값
print(rand)

tf.Tensor([0.22536182 0.22978973 0.38302708 0.74884987], shape=(4,), dtype=float32)


In [47]:
rand = tf.random.uniform([4,2],0,1)
print(rand)

tf.Tensor(
[[0.11217988 0.7912402 ]
 [0.65772045 0.58816636]
 [0.5107548  0.4181925 ]
 [0.45513964 0.0486275 ]], shape=(4, 2), dtype=float32)


In [48]:
rand = tf.random.uniform([6,3],0,1)
print(rand)

tf.Tensor(
[[0.7151685  0.5608511  0.80882657]
 [0.30780244 0.6108159  0.36812818]
 [0.5062866  0.45860505 0.16563082]
 [0.69936824 0.6261765  0.95697296]
 [0.7784327  0.3904543  0.9860865 ]
 [0.16439843 0.1610918  0.83018684]], shape=(6, 3), dtype=float32)


In [49]:
rand = tf.random.uniform([6,3,1],0,1)
print(rand)

tf.Tensor(
[[[0.74910915]
  [0.54838765]
  [0.35058606]]

 [[0.8677598 ]
  [0.87481105]
  [0.02007747]]

 [[0.4090923 ]
  [0.32425678]
  [0.01840937]]

 [[0.5274036 ]
  [0.00919437]
  [0.994995  ]]

 [[0.9688678 ]
  [0.5058392 ]
  [0.49150229]]

 [[0.7847806 ]
  [0.06885457]
  [0.45919716]]], shape=(6, 3, 1), dtype=float32)


## 1.3.2 정규분포(normal함수)

In [50]:
rand = tf.random.normal([4],0,1)   # 표준 정규분포 데이터(난수) 4개 생성, 0은 평균(mean), 1은 표준편차(standard deviation)
print(rand)

tf.Tensor([ 0.19837603  0.0157307   0.2773946  -1.9181962 ], shape=(4,), dtype=float32)


In [51]:
rand = tf.random.normal([6,2],0,1)
print(rand)

tf.Tensor(
[[ 1.9986647   1.4988749 ]
 [ 0.6186463  -1.5262347 ]
 [-1.0621766   2.2284079 ]
 [-0.97260123  0.272335  ]
 [ 1.2489439  -1.2368342 ]
 [ 0.571167    0.49180034]], shape=(6, 2), dtype=float32)


# 1.4 뉴런 만들기

In [52]:
# 뉴런은 입력(input), 가중치(w), 활성화 함수(f), 출력(output)으로 구성된다.
# 학습이 잘 된다는 것은 '좋은 가중치'를 얻어서 원하는 출력에 점점 가까운 값을 얻는 것
# 활성화함수(f)에는 시그모이드(sigmoid), ReLU 등이 주로 쓰인다.

In [53]:
# 여기서는 출력을 0 ~ 1 사이로 제한하여  AND, OR, XOR연산을 다루는데 적합한 시그모이드 함수를 사용 

In [54]:
# 활성화 함수 Sigmoid 생성
import math
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [55]:
x = 1    # 입력값
y = 0    # 출력값
w = tf.random.normal([1],0,1)   # 0은 평균, 1은 표준편차
output = sigmoid(x * w)
print(output)

0.8903440259082952


In [56]:
for i in range(1000):
  output = sigmoid(x * w)
  error = y - output
  w = w + x * 0.1 * error     # 0.1은 학습률

  if i % 100 == 99:
    print('반복 횟수 {0} : , 에러값 : {1}, 결과값 : {2}'.format(i,error, output))

반복 횟수 99 : , 에러값 : -0.13893008027703216, 결과값 : 0.13893008027703216
반복 횟수 199 : , 에러값 : -0.06122529839567363, 결과값 : 0.06122529839567363
반복 횟수 299 : , 에러값 : -0.03865118427565664, 결과값 : 0.03865118427565664
반복 횟수 399 : , 에러값 : -0.028121908123707216, 결과값 : 0.028121908123707216
반복 횟수 499 : , 에러값 : -0.022063946723261153, 결과값 : 0.022063946723261153
반복 횟수 599 : , 에러값 : -0.018138056901626773, 결과값 : 0.018138056901626773
반복 횟수 699 : , 에러값 : -0.015390813856214661, 결과값 : 0.015390813856214661
반복 횟수 799 : , 에러값 : -0.01336226874462837, 결과값 : 0.01336226874462837
반복 횟수 899 : , 에러값 : -0.01180381148225498, 결과값 : 0.01180381148225498
반복 횟수 999 : , 에러값 : -0.01056946132251417, 결과값 : 0.01056946132251417


In [57]:
x = 1
y = 0
w = tf.random.normal([1],0, 0.03)   # 평균이 0이고, 표준편차가 0.03
# w = tf.random.uniform([1],0,1)    # 최대값이 0이고, 최소값이 1

for i in range(3000):               # 3000번 학습
  output = sigmoid(x * w)
  error = y - output
  a = 0.4                           # 학습률은 0.4
  w = w + x * a * error

  if i % 100 == 99:
    print('반복 횟수 {0} : , 에러값 : {1}, 결과값 : {2}'.format(i,error, output))


반복 횟수 99 : , 에러값 : -0.025907280843080437, 결과값 : 0.025907280843080437
반복 횟수 199 : , 에러값 : -0.012816700686036419, 결과값 : 0.012816700686036419
반복 횟수 299 : , 에러값 : -0.008496893252349126, 결과값 : 0.008496893252349126
반복 횟수 399 : , 에러값 : -0.006351022177760097, 결과값 : 0.006351022177760097
반복 횟수 499 : , 에러값 : -0.005069107109994612, 결과값 : 0.005069107109994612
반복 횟수 599 : , 에러값 : -0.004217181591161548, 결과값 : 0.004217181591161548
반복 횟수 699 : , 에러값 : -0.0036101081597546365, 결과값 : 0.0036101081597546365
반복 횟수 799 : , 에러값 : -0.003155651379320181, 결과값 : 0.003155651379320181
반복 횟수 899 : , 에러값 : -0.002802721535608671, 결과값 : 0.002802721535608671
반복 횟수 999 : , 에러값 : -0.0025207239413927683, 결과값 : 0.0025207239413927683
반복 횟수 1099 : , 에러값 : -0.0022902372002170926, 결과값 : 0.0022902372002170926
반복 횟수 1199 : , 에러값 : -0.0020983426513507724, 결과값 : 0.0020983426513507724
반복 횟수 1299 : , 에러값 : -0.0019361012223034916, 결과값 : 0.0019361012223034916
반복 횟수 1399 : , 에러값 : -0.0017971308849060524, 결과값 : 0.0017971308849060524
반복 횟수

In [58]:
x = 0           # 입력값
y = 1           # 출력값
w = tf.random.normal([1], 0,1)

for i in range(1000):
  output = sigmoid(x * w)
  error = y - output
  w = w + x * 0.1 * error

  if i % 100 == 99:
    print('반복 횟수 {0} : , 에러값 : {1}, 결과값 : {2}'.format(i,error, output))

# 에러값이 변하지 않고, 결과값도 0.5에서 변하지 않고있는 문제 발생.
# WHY?  입력값을 0을 넣었기 때문에 가중치의 값이 변하지 않음  / Y = f(X * w + 1 * b) 경사하강법 업데이트 식을 통해 알 수 있음
# SO?   편향(bias)을 뉴런에 넣어줘야함. 참고로 편향의 입력에는 보편적으로 1을 넣어줌 

반복 횟수 99 : , 에러값 : 0.5, 결과값 : 0.5
반복 횟수 199 : , 에러값 : 0.5, 결과값 : 0.5
반복 횟수 299 : , 에러값 : 0.5, 결과값 : 0.5
반복 횟수 399 : , 에러값 : 0.5, 결과값 : 0.5
반복 횟수 499 : , 에러값 : 0.5, 결과값 : 0.5
반복 횟수 599 : , 에러값 : 0.5, 결과값 : 0.5
반복 횟수 699 : , 에러값 : 0.5, 결과값 : 0.5
반복 횟수 799 : , 에러값 : 0.5, 결과값 : 0.5
반복 횟수 899 : , 에러값 : 0.5, 결과값 : 0.5
반복 횟수 999 : , 에러값 : 0.5, 결과값 : 0.5


In [59]:
x = 0
y = 1
w = tf.random.normal([1], 0,1)
b = tf.random.normal([1], 0,1)

for i in range(1000):
  output = sigmoid(x * w + 1 * b)
  error = y - output
  w = w + x * 0.1 * error
  b = b + 1 * 0.1 * error

  if i % 100 == 99:
    print('반복 횟수 {0} :, 에러값 : {1}, 결과값 : {2}'.format(i,error, output))

# error는 0에 가까워지고, output은 기대출력인 1에 가까워지고 있는걸 보아, 학습이 잘 되고 있음을 알 수 있음


반복 횟수 99 :, 에러값 : 0.09581782088576396, 결과값 : 0.904182179114236
반복 횟수 199 :, 에러값 : 0.0505554215362547, 결과값 : 0.9494445784637453
반복 횟수 299 :, 에러값 : 0.03402869922297602, 결과값 : 0.965971300777024
반복 횟수 399 :, 에러값 : 0.02557098765127419, 결과값 : 0.9744290123487258
반복 횟수 499 :, 에러값 : 0.020454285554998064, 결과값 : 0.9795457144450019
반복 횟수 599 :, 에러값 : 0.017032267650002875, 결과값 : 0.9829677323499971
반복 횟수 699 :, 에러값 : 0.014585305955279626, 결과값 : 0.9854146940447204
반복 횟수 799 :, 에러값 : 0.012749839092052517, 결과값 : 0.9872501609079475
반복 횟수 899 :, 에러값 : 0.011322718140588828, 결과값 : 0.9886772818594112
반복 횟수 999 :, 에러값 : 0.01018165504063362, 결과값 : 0.9898183449593664


# 2.1 첫번째 신경망 네트워크 : AND

In [60]:
# AND,OR,XOR연산은 x(입력값)는 1이고, y(출력값)는 0인 sigmoid함수를 사용한다.

In [61]:
# AND연산 : 입력값이 모두 참일때만, 결과값도 참이 되는 것

In [62]:
print(int(True))
print(int(False))

1
0


In [63]:
# 넘파이를 불러오는 코드
import numpy as np

# 입력값을 array로 표현 / 입력값이 2개 이상일 땐, 가장 바깥에 대괄호[]가 하나 더 있는 2중 대괄호 형태.
x = np.array([[1,1],[1,0],[0,1],[0,0]])

# AND연산자의 출력값
y = np.array([[1],[0],[0],[0]])

# 가중치 정의 - 입력값이 2개, 평균 0, 표준편차 1 / 무작위 값 2개 생성
w = tf.random.normal([2],0,1)

# 편향은 항상 1
b = tf.random.normal([1],0,1)

# 편향의 고정값
b_x = 1

# range()함수를 활용한 반복 학습 횟수 결정
for i in range(2000):
  error_sum = 0        # 기본 결과값은 0값

  for j in range(4):
    output = sigmoid(np.sum(x[j]*w)+b_x*b)
    error = y[j][0] - output

    # 무작위로 선정된 가중치와 편향값은 경사하강법을 통해 값을 업데이트해준다.
    w = w + x[j] * 0.1 * error
    b = b + b_x * 0.1 * error

    error_sum += error

# 결과 표시
  if i % 200 == 199:
    print(i, error_sum)

199 -0.10287696317630421
399 -0.06300579168817687
599 -0.04527859976213118
799 -0.03523861533101001
999 -0.028793330357195432
1199 -0.02431415660722593
1399 -0.021025159325694695
1599 -0.01851105599519166
1799 -0.016528380645407056
1999 -0.014924418659451644


In [64]:
import numpy as np
x = np.array([[1,1],[1,0],[0,1],[0,0]])
y = np.array([[1],[0],[0],[0]])

In [65]:
w = w + x[j] * 0.1 * error # 가중치 갱신

In [66]:
# 넘파이를 활용한 원소에 대한 개산
import numpy as np
print(np.array([1,2,3])*2)
print(np.array([1,2,3])*0)
print(np.array([1,2,3])*-1)
print(np.array([1,2,3])*0.01)

# 결과값이 리스트가 아닌 넘파이여서 쉼표(,)가 없음.

[2 4 6]
[0 0 0]
[-1 -2 -3]
[0.01 0.02 0.03]


In [67]:
# 일반 리스트 연산
print([1,2,3]*2)
print([1,2,3]*0)
print([1,2,3]*-1)

[1, 2, 3, 1, 2, 3]
[]
[]


In [68]:
# 리스트에 정수가 아닌 수는 곱할 수 없다.
# print([1,2,3]* 0,01)  # 오류발생

In [69]:
# 확인하기
for i in range(4):
  print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))
  
# 업데이트 될 수록 결과값은 0에 가까워지고 있다.

X: [1 1] Y: [1] Output: 0.9651584840890578
X: [1 0] Y: [0] Output: 0.024691832355806922
X: [0 1] Y: [0] Output: 0.024766848517140533
X: [0 0] Y: [0] Output: 2.3209313101993077e-05


In [70]:
print("AND 연산 가중치 및 편향 ")
print("w:",w)
print("b:",b)

# 첫번째 가중치와 두번째 가중치가 비슷하다는 것은 비슷한 중요도를 갖는다는 뜻.
# 편향값은 확실한 음수 

AND 연산 가중치 및 편향 
w: tf.Tensor([6.9946527 6.997763 ], shape=(2,), dtype=float32)
b: tf.Tensor([-10.670934], shape=(1,), dtype=float32)


# 2.2 두번째 신경망 네트워크 : OR

In [71]:
# OR연산 : 입력값이 모두 거짓일때만, 결과값도 거짓이 되는 것

In [72]:
import numpy as np
x = np.array([[1,1],[1,0],[0,1],[0,0]])
y = np.array([[1],[1],[1],[0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
  error_sum = 0
  for j in range(4):
    output = sigmoid(np.sum(x[j]*w)+b_x*b)
    error = y[j][0] - output
    w = w + x[j] * 0.1 * error
    b = b + b_x * 0.1 * error
    error_sum += error

  if i % 200 == 199:
    print(i, error_sum)

# 최종 에러값이 점차 줄어들고 있음을 확인할 수 있다.

199 -0.04535172900518375
399 -0.02467624268377233
599 -0.01683885187719586
799 -0.012737382139598782
999 -0.010224855230156121
1199 -0.008531880670983587
1399 -0.00731545584611578
1599 -0.006399554359295005
1799 -0.005686520491942421
1999 -0.005113953560702381


In [73]:
for i in range(4):
  print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

# 학습 수가 커질수록 실제출력이 기대 출력에 가까워지고 있다는 것을 알 수 있음

X: [1 1] Y: [1] Output: 0.9999972634537471
X: [1 0] Y: [1] Output: 0.9898539979529972
X: [0 1] Y: [1] Output: 0.989842440605204
X: [0 0] Y: [0] Output: 0.025357266235283178


#2.3 세번째 신경망 네트워크 : XOR

In [74]:
# XOR연산 : 홀수개의 입력이 참일때만, 결과가 참이 되는 것

In [75]:
import numpy as np
x = np.array([[1,1],[1,0],[0,1],[0,0]])
y = np.array([[0],[1],[1],[0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
  error_sum = 0
  for j in range(4):
    output = sigmoid(np.sum(x[j]*w+ b_x*b))
    error = y[j][0] - output
    w = w + x[j] * 0.1 * error
    b = b + b_x * 0.1 * error
    error_sum += error

  if i % 200 == 199:
    print(i, error_sum)

# 어랏..? 어느순간 error_sum이 변하지 않고있다. 

199 -0.0012332667776796535
399 -2.147123196916123e-05
599 -3.756836579604794e-07
799 -3.161695172337886e-08
999 -3.161695172337886e-08
1199 -3.161695172337886e-08
1399 -3.161695172337886e-08
1599 -3.161695172337886e-08
1799 -3.161695172337886e-08
1999 -3.161695172337886e-08


In [76]:
for i in range(4):
  print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

# X가 변해도 Output(학습 결과값)은 0.5 근처에서 머물고 있다. 왜일까?

X: [1 1] Y: [0] Output: 0.522711139495212
X: [1 0] Y: [1] Output: 0.5227111580832337
X: [0 1] Y: [1] Output: 0.4967533592088731
X: [0 0] Y: [0] Output: 0.4967533759719726


In [77]:
# 신경망 학습에서 중요한 것은 가중치(w)와 편향(b)이다.
# 가중치와 편향이 '경사하강법'을 통해 점차 에러를 극복하기 때문!

In [78]:
# 어째서 위와 같은 결과가 나왔는지 확인해보기 위해 '가중치 값'과 '편향 값'을 한 번 출력해보자.
print('w:', w)      # 첫번째 입력값의 가중치: 0.1038... 두번째 입력값의 가중치: 0.0000...
print('b:', b)      # 편향 값: 너무 작은 값

w: tf.Tensor([ 1.0389386e-01 -6.7055225e-08], shape=(2,), dtype=float32)
b: tf.Tensor([-0.01298668], shape=(1,), dtype=float32)


In [79]:
print("XOR 연산 가중치 및 편향 ")
print('w:',w)
print('b:',b)

# 첫번째 가중치, 두번째 가중치, 편향이 모두 비슷해 그 의미를 알기 어려움

XOR 연산 가중치 및 편향 
w: tf.Tensor([ 1.0389386e-01 -6.7055225e-08], shape=(2,), dtype=float32)
b: tf.Tensor([-0.01298668], shape=(1,), dtype=float32)


In [79]:
# 이러한 이유로 1970년~1980년 인공지능의 암흑기('인공지능의 겨울')를 맞이하게 된다.
# 하지만 연구자들은 여기서 포기하지 않고, 이를 해결 할 다른 방법을 찾게 되는데..
# 이는 다음 시간에 이어서 ~~~~~~~~~c