<a href="https://colab.research.google.com/github/dianakang/K_digital_likelion/blob/master/%ED%86%A0%ED%81%B0%ED%99%94(week_6).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.1.1 토크나이징

In [ ]:
# 우리가 일상에서 사용하는 언어를 '자연어'라고 한다.
# 컴퓨터는 자연어를 직접 이해할 수 없다. 따라서 컴퓨터가 이해할 수 있도록 처리해줘야 하는데, 그것을 자연어처리(Natural Language Processing, NLP)라고 한다.

In [ ]:
# 그럼 어떻게 해야 컴퓨터에게 자연어를 이해시킬 수 있을까?
# 우선 어떤 문장을 일정한 의미가 있는 가장 작은 단어들로 나눈다. 그 다음 나눠진 단어들을 이용해 의미를 분석한다.
# 여기서 가장 기본이 되는 단어들을 '토큰(token)'이라고 한다. 
# 그리고 문장에서 토큰 단위로 정보를 나누는 작업을 '토크나이징'이라고 한다.

# 1.1.2 KoNLPy

In [ ]:
# 토크나이징은 문장 형태의 데이터를 처리하기 위해 제일 처음 수행해야 하는 전처리 작업이다.
# 한국어 토크나이징을 지원하는 파이썬 모듈(라이브러리)에는 KoNLPy(코엔엘파이)가 있다. 오픈소스 소프트웨어이다. 
# 한국어 자연어 처리를 할 때 토큰 단위는 '형태소'이다.
# '형태소'란 일정한 의미가 있는 가장 작은 말의 단위이다. 즉, 의미가 더 이상 쪼개지지 않는 단어를 뜻한다.

In [ ]:
# 그럼 문장을 어떻게 형태소 단위로 토크나이징 할 수 있을까?
# 영어의 경우 단어의 변화가 크지 않고, 띄어쓰기로 단어를 구분하기 때문에 공백을 기준으로 토크나이징을 수행해도 큰 문제가 없다.
# 하지만 한국어의 경우에는 언어의 특성상 띄어쓰기만으로 토크나이징을 하는 것이 어렵다.
# 따라서 한국어 문장에서 형태소를 분석할 수 있는 도구가 필요한데, 이를 '형태소 분석기'라고 한다.
# 이는 문장에서 형태소뿐만 아니라 어근, 접두사/접미사, 품사 등 다양한 언어적 속성의 구조를 파악하게 해주며, 형태소의 듯과 문맥을 고려해 품사 태깅을 해준다.

In [ ]:
# 그럼 이제 KoNLPy을 설치한 후 사용하기 좋은 세 가지 형태소 분석기 모듈을 살펴보자.

In [ ]:
pip install konlpy

     |████████████████████████████████| 19.4MB 1.3MB/s 
     |████████████████████████████████| 460kB 69.3MB/s 
     |████████████████████████████████| 92kB 12.3MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0


## (1) Kkma

In [ ]:
# Kkma는 '꼬꼬마'라고 불린다.

In [ ]:
from konlpy.tag import Kkma
# konlpy.tag 패키지의 Kkma 모듈을 불러온다.

In [ ]:
# Kkma에서 사용하는 4가지 함수
## morphs(phrase) -> 형태소 단위로 토크나이징 / 리스트 형태로 반환
## nouns(phrase) -> 품사가 명사인 토큰만 추출
## pos(phrase,flatten=True) -> 형태소 추출 후 품사 태깅 / 튜플{}형태로 묶여서 리스트[]로 반환
## sentences(phrase) -> 문장 분리 / 리스트 형태로 반환

In [ ]:
# 꼬꼬마 형태소 분석기 객체 생성
kkma = Kkma()

In [ ]:
text = "인공지능 챗봇 이루다는 연애의 과학에서 학습했습니다."

In [ ]:
# 형태소 추출
morphs = kkma.morphs(text)  ## text변수에 저장된 문장을 형태소 단위로 토크나이징 
print(morphs)   ## 토크나이징된 형태소들은 리스트 형태로 반환

['인공지능', '챗봇', '이루', '달', '는', '연애', '의', '과학', '에서', '학습', '하', '었', '습니다', '.']


In [ ]:
# 형태소와 품사 태그 추출
pos = kkma.pos(text)   ## text변수에 저장된 문장을 품사 태깅
print(pos)        ## 태깅된 품사와 형태소들은 리스트 형태로 반환

[('인공지능', 'NNG'), ('챗봇', 'UN'), ('이루', 'NNG'), ('달', 'VV'), ('는', 'ETD'), ('연애', 'NNG'), ('의', 'JKG'), ('과학', 'NNG'), ('에서', 'JKM'), ('학습', 'NNG'), ('하', 'XSV'), ('었', 'EPT'), ('습니다', 'EFN'), ('.', 'SF')]


In [ ]:
# 명사만 추출
nouns = kkma.nouns(text)  
print(nouns)

['인공', '인공지능', '지능', '챗봇', '이루', '연애', '과학', '학습']


In [ ]:
# 문장 구분(분리)
sentences = "국내 코스피가 3000선을 돌파하였습니다! 이번 해는 정말 기대가 되네요!"
s = kkma.sentences(sentences)   ## 복합 문장(2개 이상의 문장)이 있을 때 문장 단위로 토크나이징
print(s)

['국내 코스 피가 3000 선을 돌파하였습니다!', '이번 해는 정말 기대가 되네요!']


In [ ]:
# Kkma는 다른 형태소 분석기에 비해 분석 시간은 느리지만, 품사 태그가 다양하다는 장점이 있음.

## (2)  Komoran

In [ ]:
# Komoran은 코모란이라고 불리며, 공백이 포함된 형태소 단위로도 분석이 가능하다는 특징이 있다. 

In [ ]:
from konlpy.tag import Komoran
# konlpy.tag 패키지의 Komoran 모듈을 불러온다.

In [ ]:
# Komoran에서 사용하는 3가지 함수
## morphs(phrase) -> 형태소 단위로 토크나이징 / 리스트 형태로 반환
## nouns(phrase) -> 품사가 명사인 토큰들만 추출
## pos(phrase, flatten = True) -> 형태소를 추출한 후 품사 태깅 / 튜플{}형태로 묶여서 리스트[]로 반환

In [ ]:
# 코모란 형태소 분석기 객체 생성
komoran = Komoran()

In [ ]:
text = "거인의 어깨위에 올라서라."

In [ ]:
# 형태소 추출
morphs = komoran.morphs(text)
print(morphs)

['거인', '의', '어깨', '위', '에', '올라서', '라', '.']


In [ ]:
# 형태소와 품사 태그 추출
pos = komoran.pos(text)
print(pos)

[('거인', 'NNP'), ('의', 'JKG'), ('어깨', 'NNG'), ('위', 'NNG'), ('에', 'JKB'), ('올라서', 'VV'), ('라', 'EF'), ('.', 'SF')]


In [ ]:
# 명사만 추출
nouns = komoran.nouns(text)
print(nouns)

['거인', '어깨', '위']


In [ ]:
# Komoran은 Kkan보다 형태소를 빠르게 분석할 수 있다. 

## (3) Okt

In [ ]:
from konlpy.tag import Okt
# konlpy.tag 패키지의 Okt 모듈을 불러온다.

In [ ]:
# Okt에서 사용하는 3가지 함수
## morphs(phrase) -> 형태소 단위 토크나이징 / 리스트 형태로 반환
## nouns(phrase) -> 품사가 명사인 토큰들만 추출
## pos(phrase, stem=False, join=False) -> 형태소 추출 후 품사 태깅 / 튜플{}형태로 묶여서 리스트[]로 반환
## normalize(phrase) -> 정규화 (ex. 사랑햌ㅋㅋㅋ -> 사랑해 ㅋㅋㅋㅋ)
## phrase(phrase) -> 어구 추출 (ex. [입력]: 오늘 날씨가 좋아요. -> [출력]: '오늘','오늘 날씨','날씨')

In [ ]:
# Okt 형태소 분석기 객체 생성
okt = Okt()

text = "인공지능을 배우는 채널 에이림"
text_1 = "내가 좋아하는 가수 아리아나그란데"

In [ ]:
# 형태소 추출
morphs = okt.morphs(text)
print(morphs)

morphs = okt.morphs(text_1)
print(morphs)

['인공', '지능', '을', '배우는', '채널', '에이', '림']
['내', '가', '좋아하는', '가수', '아리아나', '그란', '데']


In [ ]:
# 형태소와 품사 태그 추출
pos = okt.pos(text)
print(pos)

pos = okt.pos(text_1)
print(pos)

[('인공', 'Noun'), ('지능', 'Noun'), ('을', 'Josa'), ('배우는', 'Verb'), ('채널', 'Noun'), ('에이', 'Noun'), ('림', 'Noun')]
[('내', 'Noun'), ('가', 'Josa'), ('좋아하는', 'Adjective'), ('가수', 'Noun'), ('아리아나', 'Noun'), ('그란', 'Modifier'), ('데', 'Noun')]


In [ ]:
# 명사만 추출
nouns = okt.nouns(text)
print(nouns)

['인공', '지능', '채널', '에이', '림']


In [ ]:
# 정규화
text_2 = "롤 한판 하실래욬ㅋㅋㅋㅋ?"
normalize = okt.normalize(text_2)
print(normalize)

롤 한판 하실래요ㅋㅋㅋ?


In [ ]:
# 어구 추출
phrases = okt.phrases(text_2)
print(phrases)

['롤 한판', '한판']


In [ ]:
# Okt는 분석되는 품사 정보는 작지만 분석 속도는 제일 빠르다. 또한 normalize()함수로  오타가 섞인 문장을 정규화할 수 있다는 장점이 있다.

# 1.2.1 사용사 사전 구축

In [ ]:
# 새롭게 생겨나는 단어나 문장은 형태소 분석기에서 인식이 안되는 경우가 많다. 
# 이를 해결하기 위해 대부분의 형태소 분석기들은 사용자 사전을 추가할 수 있도록 구성되어 있다.

In [ ]:
# 우리는 Komoran을 선택해서 사용할 것이다.
from konlpy.tag import Komoran

komoran = Komoran(userdic='/content/drive/MyDrive/6주차')
text = "에이림은 최고의 인공지능스터디 플랫폼이야"
pos = komoran.pos(text)
print(pos)

[('에', 'NNG'), ('이림', 'NNP'), ('은', 'JX'), ('최고', 'NNG'), ('의', 'JKG'), ('인공지능', 'NNP'), ('스터디', 'NNG'), ('플랫폼', 'NNP'), ('이야', 'JX')]


In [ ]:
# '에이림'이라는 단어를 '에','이림'으로 분리해 인식해버렸다. 단어 토큰을 사용해 의미를 분석하는 챗봇의 경우에는 오류를 낼 확률이 높다.
# 이를 해결하려면 Komoran의 사용자 사전에 '에이림'이라는 신규 단어를 등록해야한다. 

In [ ]:
from konlpy.tag import Komoran

komoran = Komoran()
text = "올해 모두 건강하시고 행복만 가득하길 바라요"

pos = komoran.pos(text)
print(pos)


[('올해', 'NNG'), ('모두', 'MAG'), ('건강', 'NNG'), ('하', 'XSV'), ('시', 'EP'), ('고', 'EC'), ('행복', 'NNG'), ('만', 'JX'), ('가득', 'MAG'), ('하', 'XSV'), ('기', 'ETN'), ('ㄹ', 'JKO'), ('바라', 'VV'), ('요', 'EC')]


In [ ]:
# 메모장을 열어 단어와 품사를 직접 등록해보자. 구분은 반드시 Tab으로 해야한다. 
komoran = Komoran(userdic='/content/drive/MyDrive/6주차/user_dic.tsv')
text = "올해 모두 건강하시고 행복만 가득하길 바라요"

pos = komoran.pos(text)
print(pos)

[('올해', 'NNG'), ('모두', 'MAG'), ('건강', 'NNG'), ('하', 'XSV'), ('시', 'EP'), ('고', 'EC'), ('행복', 'NNG'), ('만', 'JX'), ('가득', 'MAG'), ('하', 'XSV'), ('기', 'ETN'), ('ㄹ', 'JKO'), ('바라', 'VV'), ('요', 'EC')]


In [ ]:
# 지금까지 한국어 토크나이징을 알아보았다. 한국어의 경우 명사와 조사를 띄어쓰지 않고, 용언에 따라 여러 가지 어미가 붙기 때문에 띄어쓰기만으로는 토크나이징을 할 수 없다.
# 따라서 KoNLPy의 형태소 분석기를 이용해 형태소 단위의 토큰과 품사 정보까지 추출하였다. 
# 그리고 추출된 정보에서 필요 없는 정보를 제거하는 과정이 추가되어야 한다. 이를 '전처리'라고 한다.
# 전처리 과정은 챗봇 엔진에서 문장의 의미나 의도를 빠르게 잘 분석하기 위해 필수적으로 거쳐야 하는 작업이다.

# 2.1.1 임베딩

In [ ]:
# 컴퓨터는 수치 연산만 가능하기 때문에 자연어를 숫자나 벡터 형태로 변환할 필요가 있다. 이를 '임베딩'이라고 한다.
# 즉, 임베딩은 단어나 문장을 수치화해 벡터 공간으로 표현하는 과정을 의미한다.
# 이러한 임베딩은 말뭉치의 의미에 따라 벡터화하기 때문에 문법적인 정보가 포함되어 있다.

In [ ]:
# 임베딩 기법에는 '문장 임베딩'과 '단어 임베딩'이 있다.
# '문장 임베딩'은 문장 전체를 벡터로 표현하는 방법이며, '단어 임베딩'은 개별 단어를 벡터로 표현하는 방법이다.
# '문장 임베딩'의 경우 전체 문장의 흐름을 파악해 벡터로 변환하기 때문에 문맥적 의미를 지니는 장점이 있다.
# 그러한 이유로 단어 임베딩에 비해 품질이 좋으며 상용 시스템이 많이 사용된다. 하지만 많은 문장 데이터가 필요하며 학습하는데 비용이 많이 들어간다.
# '단어 임베딩'은 동음이의어에 대한 구분을 하지 않기 때문에 의미가 다르더라도 단어의 형태가 같다면 동일한 벡터값으로 표현되는 단점이 있다.
# 하지만 학습 방법이 간단하고 컴퓨터에서 처리하기에 효과적이라는 장점이 있다. 

# 2.1.2 원-핫 인코딩

In [ ]:
# 원-핫 인코딩은 단어를 숫자 벡터로 변환하는 가장 기본적인 방법이다.
# 요소들 중 단 하나의 값만 1이고, 나머지 요솟값은 0인 인코딩을 의미한다.
# 원-핫 인코딩으로 나온 결과를 원-핫 벡터라고 하며, 전체 요소 중 단 하나의 값만 1이기 때문에 '희소벡터'라고도 한다.

In [ ]:
# 원-핫 인코딩을 하기 위해서는 단어 집합이라 불리는 사전을 먼저 만들어야 한다.
# 여기서 사전은 말뭉치에서 나오는 서로 다른 모든 단어의 집합을 의미한다. 말뭉치에 존재하는 모든 단어의 수가 원-핫 벡터의 차원을 결정한다.
# 예를 들어 100개의 단어가 존재한다면 원-핫 벡터의 크기는 100차원이 된다. 사전이 구축되었다면 사전 내 단어 순서대로 고유한 인덱스 번호가 부여된다.


In [ ]:
# pip install konlpy
from konlpy.tag import Komoran

In [ ]:
import numpy as np
komoran = Komoran(userdic ='/content/drive/MyDrive/6주차/user_dic.tsv')


In [ ]:
text = "내가 좋아하는 커피는 라테야. 하지만 오늘은 아메리카노를 마실래"

In [ ]:
# 명사만 추출
nouns = komoran.nouns(text)
print(nouns)

['커피', '라테', '오늘', '아메리카노']


In [ ]:
# 단어 사전 구축 및 단어별 인덱스 부여
dics = {}   ## 빈 사전 형식을 구축합니다.
for word in nouns:    
## 앞서 설정한 nouns의 값을 하나씩 받아오기 위해 반복문을 활용합니다.
  if word not in dics.keys():
## 이 과정은 사전에 같은 단어가 반복적으로 들어오는 것을 방지하기 위한 조건문입니다. 
## ※ 'not in' 확인하기
    dics[word] = len(dics)
## 앞서 설정한 dics를 활용하여 사전(dics)의 [word]로 할당하여 줍니다.

print(dics)

{'커피': 0, '라테': 1, '오늘': 2, '아메리카노': 3}


In [ ]:
# 원-핫 인코딩
nb_classes      = len(dics)   # 원-핫 벡터 차원의 크기를 결정한다. 단어 사전은 크기가 원-핫 벡터의 크기이다.
print(nb_classes)
targets         = list(dics.values())
print(targets)
one_hot_targets = np.eye(nb_classes)[targets] # 원 - 핫 벡터를 만들기 위해서는 넘파이의 eye()함수를 이용할 수 있다.
# eye()함수는 단위행렬을 만들어 준다. eye()함수의 인자 크기대로 단위행렬을 반환하며, eye()함수 뒤에 붙은 [targets]을 이용해 생성된 단위행렬의 순서를 단어 사전의 순서에 맞게 정렬해준다.
print(one_hot_targets)

4
[0, 1, 2, 3]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 원-핫 인코딩의 경우 간단한 구현 방법에 비해 좋은 성능을 가지기 때문에 많은 사람들이 사용하고 있다.
# 하지만 단순히 단어의 순서에 의한 인덱스값을 기반으로 인코딩된 값이기 때문에 단어의 의미나 유사한 단어와의 관계를 담고 있지 않다. 즉, 비선형적이다.
# 또한 단어 사전의 크기가 커짐에 따라 원-핫 벡터의 차원도 커지는데 이때 메모리 낭비와 계산의 복잡도가 커지고, 대부분의 요소가 0의 값을 가지고 있으므로 비효율적이다.

## 2.1.3 희소 표현과 분산 표현

### (1) 희소 표현

In [ ]:
# 앞서 소개한 원-핫 인코딩은 표현하고자 하는 단어의 인덱스 요소만 1이고 나머지 요소는 모두 0으로 표현되는 희소벡터(또는 희소행렬)이다. 
# 이처럼 단어가 희소 벡터로 표현되는 방식을 희소표현이라고 부른다.
# '희소 표현'은 각각의 차원이 독립적인 정보를 지니고 있어 사람이 이해하기에 직관적인 장점이 있지만, 단어 사전의 크기가 커질수록 메모리 낭비와 계산 복잡도가 커지는 단점도 있다.
# 또한 단어 간의 연관성이 전혀 없어 의미를 담을 수 없다.

### (2) 분산 표현

In [ ]:
# 자연어 처리를 잘 하기 위해서는 '기본 토큰이 되는 단어의 의미'와 '주변 단어 간의 관계'가 단어 임베딩에 표현되어야 한다. 하지만 희소표현의 경우 그러지 못한다.
# 이를 해결하기 위해 각 단어 간의 유사성을 잘 표현하면서도 벡터 공간을 절약할 수 있는 방법을 고안했는데 이를 '분산 표현'이라고 한다.
# '분산 표현'은 한 단어의 정보가 특정 차원에 표현되지 않고 여러 차원에 분산되어 표현된다하여 붙여진 이름이다. 즉, 하나의 차원에 다양한 정보를 가지고 있다.
# 대표적으로 색상을 표현하는 RGB모델은 3차원 형태의 벡터로 생각할 수 있으며, 분산 표현 방식이다. 예를 들어 연두색은 RGB(204, 255, 204)형태로 분산표현을 하는 것이다.
# 이를 0과 1으로만 이루어진 희소 표현으로 한다면 벡터 차원의 크기는 엄청날 것이다. 뿐만 아니라 다른 색상과의 유사성도 파악할 수 없을 것이다.
# 이처럼 분산표현은 희소표현에 비해 장점이 많아 단어 임베딩 기법에서 많이 사용되고 있는 방식이다.

In [ ]:
# 이처럼 분산 표현 방식을 사용하면 단어 임베딩 벡터가 더 이상 희소하지 않다. 신경망에서는 분산 표현을 학습하는 과정에서 임베딩 벡터의 모든 차원에 의미 있는 데이터를 고르게 밀집시킨다. 
# 이 때문에 희소 표현과 반대로 데이터 손실을 최소화하면서 벡터 차원이 압축되는 효과가 생긴다. 
# 분산 표현은 우리가 원하는 차원에 데이터를 최대한 밀집시킬 수 있어 밀집 표현이라 부르기도 하며, 밀집 표현으로 만들어진 벡터를 '밀집 벡터'라 한다.

In [ ]:
# 분산 표현의 장점
# 1. 임베딩 벡터의 차원을 데이터 손실을 최소화하면서 압축할 수 있다. Cf) '희소 표현' => 입력 데이터의 차원이 너무 높아지면 신경망 모델의 학습이 어려워지는 '차원의 저주' 문제가 발생
# 2. 단어의 의미, 주변 단어간의 관계 등 많은 정보가 표현되어 있어 일반화 능력이 뛰어나다. => ex) '여자' - '여성'을 구별할 수 있다.
## 벡터 공간 상에서 유사한 의미를 갖는 단어들은 비슷한 위치에 분포되어 있기 때문에 '여자'와 '여성'의 단어 위치는 매우 가깝다. 
## 이런 두 단어 간의 거리를 계산할 수 있으면 컴퓨터는 '여자'와 '여성' 두 단어를 같은 의미로 해석할 수 있다.

# 3.1.1 Word2Vec

In [ ]:
# 신경망 기반 단어 임베딩의 대표적인 방법 -> Word2Vec
## Word2Vec은 2013년에 구글에서 발표했으며 가장 많이 사용하고 있는 단어 임베딩 모델이다.
## 이 모델은 CBOW(continuous bag - of words)와 skip-gram 두 가지 모델로 제안되었다.

In [ ]:
# CBOW 모델
## CBOW모델은 맥락(context word)이라 표현되는 주변 단어들을 이용해 타겟 단어를 예측하는 신경망 모델이다.
## 신경망의 입력을 주변 단어들로 구성하고, 출력을 타깃 단어로 설정해 학습된 가중치 데이터를 임베딩 벡터로 활용한다.
## CBOW 모델에서는 타깃 단어를 예측하기 위해 앞뒤 단어를 확인했다. 이 때 앞뒤로 몇 개의 단어까지 확인할지 결정할 수 있는데, 이 범위를 윈도우(window)라고 한다.

In [ ]:
# skip-gram 모델
## 하나의 타깃 단어를 이용해 주변 단어들을 예측하는 신경망 모델이다.
## 입출력이 CBOW모델과 반대로 되어있기 때문에 skip-gram모델이 CBOW 모델에 비해 예측해야 하는 맥락이 많아진다.
## 따라서 단어 분산 표현력이 우수해 CBOW 모델에 비해 임베딩 품질이 우수하다.
## 반면, CBOW 모델은 타깃 단어의 손실만 계산하면 되기 때문에 학습 속도가 빠른 장점이 있다.

In [ ]:
# Word2Vec의 단어 임베딩은 해당 단어를 밀집 벡터로 표현하며 학습을 통해 의미상 비슷한 단어들을 비슷한 벡터 공간에 위치시킨다.
# 또한 벡터 특성상 의미에 따라 방향성을 갖게된다. 임베딩된 벡터들 간 연산이 가능하기 때문에 단어간 관계를 계산할 수 있다.

In [ ]:
pip install KoNLPy

In [ ]:
from gensim.models import Word2Vec
from konlpy.tag import Komoran
import time

In [ ]:
# 한국어 Word2Vec를 만들기 위해서는 한국어 말뭉치를 수집해야 한다. 네이버 영화 리뷰를 이용해 Word2Vec 모델을 만들어보자.

In [ ]:
# 네이버 영화 리뷰 데이터 읽어옴
def read_review_data(filename):     # read_review_data()함수는 리뷰 데이터를 각 라인 별로 읽어와 \t를 기준으로 데이터를 분리한다. 그 후 첫 번째 행의 헤더를 제거하고 리뷰 데이터만 반환한다.
  with open(filename, 'r') as f:
    data = [line.split('\t') for line in f.read().splitlines()]
    data = data[1:]   # header 제거
  return data

In [ ]:
# 현재 시간 측정 시작
start = time.time()

# 리뷰 파일 읽어오기
print('1) 말뭉치 데이터 읽기 시작')
review_data = read_review_data('/content/drive/MyDrive/6주차/ratings.txt')  # read_review_data()함수를 호출해 현재 경로에 있는 ratings.txt파일을 리스트 형태로 읽어온다.
print(len(review_data))  # 리뷰 데이터 전체 개수
print('1) 말뭉치 데이터 읽기 완료: ', time.time() - start) # 데이터 읽는데 소요되는 시간 측정

1) 말뭉치 데이터 읽기 시작
200000
1) 말뭉치 데이터 읽기 완료:  0.45798158645629883


In [ ]:
# 문장단위로 명사만 추출해 학습 입력 데이터로 만듬
print('2) 형태소에서 명사만 추출 시작')
komoran = Komoran()     # Komoran 형태소 분석기를 이용해 불러온 리뷰 데이터에서 문장별로 명사만 추출한다. 
docs = [komoran.nouns(sentence[1]) for sentence in review_data]     #  sentence[1]은 rating.txt파일에서 document 컬럼의 데이터를 의미한다. 
print('2) 형태소에서 명사만 추출 완료:', time.time() - start)

2) 형태소에서 명사만 추출 시작
2) 형태소에서 명사만 추출 완료: 6151.034969568253


In [ ]:
# word2vec 모델 학습
print('3) word2vec 모델 학습 시작')             # sentences = Word2Vec 모델 학습에 필요한 문장 데이터(입력값) / size = 단어 임베딩 벡터의 차원(크기)
model = Word2Vec(sentences=docs, size =200, window =4, min_count=2, sg=1)    # window = 주변 단어 윈도우 크기 /  hs = 0(0이 아닌 경우 음수 샘플링 사용, 1(모델 학습에 softmax사용)
print('3) word2vec 모델 학습 완료: ', time.time() - start)     #  min_count = 단어 최소 빈도 수 제한 / sg = 0(CBOW 모델), 1(skip-gram 모델)

3) word2vec 모델 학습 시작
3) word2vec 모델 학습 완료:  6211.852521181107


In [ ]:
# 모델 저장
print('4) 학습된 모델 저장 시작')
model.save('/content/nvmc.model')
print('4) 학습된 모델 저장 완료: ', time.time() - start)

4) 학습된 모델 저장 시작
4) 학습된 모델 저장 완료:  8275.546051502228


In [ ]:
# import os
# print(os.getcwd())

/content/drive/My Drive/6주차


In [ ]:
# os.chdir('/content/drive/MyDrive/6주차')
#   # change+dir = 경로변경

In [ ]:
# print(os.getcwd())

/content/drive/My Drive/6주차


In [ ]:
# 학습된 말뭉치 개수, 말뭉치 내 전체 단어 개수
print("corpus_count : ", model.corpus_count)   # corpus = 말뭉치
print("corpus_total_words : ", model.corpus_total_words)

corpus_count :  200000
corpus_total_words :  1076896


In [ ]:
# 이제 생성된 Word2Vec 모델 파일(nvmc.model)을 읽어와 실제로 단어 임베딩된 값과 벡터 공간상의 유사한 단어들을 확인한다.
from gensim.models import Word2Vec
# 모델 로딩
model = Word2Vec.load('nvmc.model')  ## 앞서 생성한 모델 파일을 읽어와 Word2Vec 객체를 생성한다.
print("corpus_total_words : ", model.corpus_total_words)

corpus_total_words :  1076896


In [ ]:
# '사랑'이란 단어로 생성한 단어 임베딩 벡터
print('사랑 : ', model.wv['사랑'])
## 아까 size=200 설정해서 200개가 나옴

사랑 :  [ 0.01674293  0.51467186 -0.07588267  0.5123789  -0.01060495  0.07019342
  0.12742509  0.43002895  0.04758167 -0.30151933  0.05330271 -0.38831586
  0.07432814 -0.07065358  0.25120553 -0.16846009 -0.0024971   0.2222305
  0.03458407  0.25135908 -0.3866345  -0.09421609  0.11133826 -0.05075794
 -0.2874938   0.42816207  0.04822439  0.431476    0.01963828  0.19921312
  0.20904988  0.19159354 -0.14315651 -0.29762885  0.516501    0.17777888
 -0.070075   -0.31060907  0.00287258 -0.09658547  0.09623053 -0.12714906
  0.09824736  0.13891724  0.45129165 -0.07572363 -0.24889077  0.18211159
 -0.1045812  -0.13736753  0.12836139  0.06364421  0.19511682  0.37865475
 -0.13012664 -0.2883566   0.28840566  0.11584891  0.18054256  0.1680498
 -0.3812222  -0.10812126 -0.04049836  0.29437268  0.04748166  0.08426711
 -0.06646287 -0.29517213  0.2042632   0.24938314  0.07123461  0.0746418
  0.02084113 -0.03910499 -0.18127085 -0.10155111  0.06480198  0.0263683
 -0.02088292 -0.01011798  0.09046382  0.4934662  

In [ ]:
# 가장 유사한 단어 추출
from gensim.models import Word2Vec
print(model.wv.most_similar("반지의 제왕", topn=5)) 
## gensim 패키지의 model.wv.most_similarity()함수를 호출할 경우 인자로 사용한 단어와 가장 유사한 단어를 리스트로 반환해준다.
## topn인자는 반환되는 유사한 단어 수를 의미한다.

[('에이리언', 0.9522925615310669), ('엑스맨', 0.9510397911071777), ('오리지널', 0.9443783760070801), ('리부트', 0.9424226880073547), ('능가', 0.9418059587478638)]


In [ ]:
# 단어 유사도 계산 (1로 가까이 갈 수록 유사도가 높아짐)
print(model.wv.similarity(w1="스타워즈", w2="아버지"))

0.30098435


In [ ]:
print(model.wv.similarity(w1="삼성", w2 = "주식"))

0.73561066


In [ ]:
# 예제를 통해 실습해보면 놀라울 정도로 유사한 단어를 찾는 경우도 있지만, 이해하기 힘든 결과를 출력하는 경우도 있다.
# 이는 주제에 맞는 말뭉치 데이터가 부족해서 생기는 현상이니 품질 좋은 말뭉치 데이터를 학습하면 임베딩 성능이 많이 좋아진다.